export type TileType = "sword" | "shield" | "fire" | "ice" | "arrow" | "heart";
export type Tile = { type: TileType; special: "row" | "column" | "bomb" | "prism" | null };
export type DuelState = {
  seed: number;
  board: Tile[][];
  score: number;
  movesLeft: number;
  comboBest: number;
  turn: number;
  lastScore: number;
  lastClear: number[];
  lastWaves: Array<{ combo: number; cells: number[]; effects: Array<{ type: string; at: number }> }>;
  status: "playing" | "finished";
};
export type DuelMove = { first: number; second: number; score: number };
export const BOARD_SIZE: number;
export const DUEL_MOVES: number;
export const TILE_TYPES: TileType[];
export function findMatchRuns(board: Tile[][]): Array<{ orientation: "horizontal" | "vertical"; type: TileType; cells: number[] }>;
export function findMatches(board: Tile[][]): Set<number>;
export function isAdjacent(first: number, second: number): boolean;
export function hasLegalMove(board: Tile[][]): boolean;
export function createDuelState(seed?: number): DuelState;
export function resolveDuelMove(state: DuelState, first: number, second: number): { state: DuelState; accepted: boolean; reason: string | null };
export function findBestMove(state: DuelState): DuelMove | null;
export function chooseBotMove(state: DuelState, difficulty?: "easy" | "medium" | "hard"): DuelMove | null;
