// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/handikap-game/GardenCurrent.tsx": () => import("../components/mockups/handikap-game/GardenCurrent.tsx"),
  "./components/mockups/handikap-game/GardenRedesign.tsx": () => import("../components/mockups/handikap-game/GardenRedesign.tsx")
};
