const worldText = {
  brand: "ŞAFAK SAVAŞÇILARI",
  profileName: "Yolcu",
  demo: "Yerel demo profili",
  level: "Seviye",
  gold: "Altın",
  weather: "Hava",
  clear: "Açık",
  rain: "Yağmur",
  inventory: "Heybe",
  settings: "Ayarlar",
  exit: "Yolculuktan çık",
  walking: "Yürüyor",
  running: "Koşuyor",
  stopped: "Durdu",
  idle: "Dinleniyor",
  world: "Yol üzerinde",
  inventoryTitle: "Yolcu heybesi",
  settingsTitle: "Yol ayarları",
  inventoryNote: "Bu yerel demo yolculuğunda heybe henüz boş.",
  inventorySlots: ["Boş", "Boş", "Boş", "Boş", "Boş", "Boş", "Boş", "Boş"],
  settingsNote: "Ses ve görüntü tercihleri bu yolculuk için geçerlidir.",
  sound: "Yol sesleri",
  soundDescription: "Rüzgâr, uzak savaş ve adım sesleri",
  vibration: "Titreşim",
  vibrationDescription: "Desteklenen cihazlarda dokunsal bildirim",
  soundOn: "Yol seslerini kapat",
  soundOff: "Yol seslerini aç",
  vibrationOn: "Titreşimi kapat",
  vibrationOff: "Titreşimi aç",
  close: "Kapat",
  settingsOpen: "Oyun ayarlarını aç",
  controls: "Yön tuşları veya WASD ile ilerle",
} as const;

export default worldText;
